// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {pool} from '../models';
import {security} from '../models';
import {chat} from '../models';
import {library} from '../models';

export function AddPool(arg1:string):Promise<void>;

export function CreatePool(arg1:string):Promise<string>;

export function DecodeToken(arg1:string):Promise<pool.Token>;

export function GetConfigTemplate():Promise<string>;

export function GetIdentities(arg1:string):Promise<Array<security.Identity>>;

export function GetMessages(arg1:string,arg2:string,arg3:string,arg4:number):Promise<Array<chat.Message>>;

export function GetNick():Promise<string>;

export function GetPoolList():Promise<Array<string>>;

export function GetSelf():Promise<security.Identity>;

export function GetSelfId():Promise<string>;

export function GetToken(arg1:string,arg2:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function ListLibrary(arg1:string):Promise<Array<library.File>>;

export function PostMessage(arg1:string,arg2:string,arg3:string,arg4:Array<Array<number>>):Promise<string>;

export function UpdateIdentity(arg1:security.Identity):Promise<void>;
